### ISSUE TITLE
你好，询问有关版权声明的名称和链接怎么处理？

### ISSUE THREAD

**Issue by helGayhub233** [secsilm/secsilm.github.io#1]
请问这个位置在哪处理，以及链接显示yoursite在哪个文件里控制？谢谢
![20180721192745](https://user-images.githubusercontent.com/20475206/43035429-071710e2-8d22-11e8-8dc0-10559903bfaf.png)
![20180721192723](https://user-images.githubusercontent.com/20475206/43035430-0eacf6fa-8d22-11e8-8484-2c164bad9ae3.png)

**Comment by secsilm** [comment]
1. 版权显示是直接由 [archer](https://github.com/fi3ework/hexo-theme-archer) 主题提供的
2. 关于 `yoursite.com` 的问题，你需要配置**博客**根目录的 `_config.yml` 文件中的 `url` 项，填上你的地址就行了。

**Comment by helGayhub233** [comment]
thank you! 解决了问题
